### ISSUE TITLE
Requesting documentation

### ISSUE THREAD

**Issue by PrasadNR** [ptsneves/ardupilot-docker#1]
I am working on https://github.com/ArduPilot/ardupilot/pull/12006#issuecomment-545250876 . However, I am not able to figure out as to how this docker image could be used to achieve what I have mentioned in the link.

**Comment by ptsneves** [comment]
I can help.
When you start this docker an instance of Copter-3.5.5 SITL is started every time there is a connection to the port 5670.
`docker run -d --name ardupilot-simulator --rm --net=host airborne/ardupilot:latest`
This is useful because I do not need to start and restart the docker container every time i want to make a flight session. I use this in unit tests and System component tests, where i can connect to the docker in 2 forms:

1. I use a GCS that works directly with TCP mavlink, like Mission Planner, MavProxy or QGroundControl
2. socat tcp:127.0.0.1:5760 PTY,link=/tmp/PTY1,cfmakeraw,ispeed=b115200,ospeed=b115200. This creates me a virtual serial port where i can simulate a drotag serial port every time I run this command.

This a completely self contained SITL instance. It does not accept commands nor modifications. If you require different builds let me know.

**Comment by PrasadNR** [comment]
@ptsneves Thanks for the quick reply!

> This a completely self contained SITL instance.

This is great and exactly what I was looking for!

> It does not accept commands nor modifications.

:slightly_frowning_face: 

> If you require different builds let me know.

Thanks for this offer! :slightly_smiling_face: Just a request regarding my requirement. Basically, I had this plan of contributing back to the community. I have a bit of time for about a month now. My research is no longer reproducible in an easy fashion and that is why I am trying to generalise and simplify the overall setup.

1. Is it possible to somehow connect any SITL (like Webots) via ports and run this flight controller code in docker?

2. Another requirement is to be able to support multiple vehicles without requiring too much of work. Is it possible to attach two drones (quadcopters) and two rovers? Is it possible to extend this to include any or all types of vehicles supported by Ardupilot _without_ resorting to the hardcoded parameters like the port?

3. Is it possible to decouple the launching of SITL (like GUI of Webots) and ArduPilot flight controller code? Basically, ```sim_vehicle.py``` and ```.launch``` files are tightly coupled to ArduPilot and running even a simple thing like two quadcopters in one simulation is a huge task in itself.

_I would be more than happy to contribute to the code in this direction if necessary if I am just given some suggestions and insights as I am not familiar with ArduPilot codebase_ :slightly_smiling_face:

**Comment by ptsneves** [comment]
> Is it possible to somehow connect any SITL (like Webots) via ports and run this flight controller code in docker?

I am not familiar with Webots sorry, but its definitely possible to run SITL Arducopter completely standalone in docker, as I explained.

> Another requirement is to be able to support multiple vehicles without requiring too much of work. Is it possible to attach two drones (quadcopters) and two rovers? Is it possible to extend this to include any or all types of vehicles supported by Ardupilot without resorting to the hardcoded parameters like the port?

Do you mean multiple vehicles sharing the same world? If yes i think the Ardupilot provided simulator does not support. If you mean multiple vehicles running in their world independently in parallel yes.

> Another requirement is to be able to support multiple vehicles without requiring too much of work. Is it possible to attach two drones (quadcopters) and two rovers? Is it possible to extend this to include any or all types of vehicles supported by Ardupilot without resorting to the hardcoded parameters like the port?

As mentioned above this version of the Dockerfile is just for ArduCopter although if you require it is easy have different vehicles. If you do not require multiple vehicles in the same world, but copies of the same world, you just need to connect to the docker and everytime you do you will be given a clean world and clean SITL instance from scratch.

**Comment by PrasadNR** [comment]
Ok. I am closing this issue based on this comment:

> Do you mean multiple vehicles sharing the same world? If yes i think the Ardupilot provided simulator does not support.
